title: Cesar's Ramirez CIT_481 Blog 2

logo: /assets/img/mail.jpeg
description: A blog for Technology and tools for the CIT comunity
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
